package cli_test

import (
	"bytes"
	"strings"
	"testing"

	"github.com/Shaik-Sirajuddin/graft/internal/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// TestCLIConsistency walks the LIVE command tree (root + every subcommand) and
// asserts the project's help/usage conventions, so a newly added command is
// automatically checked and cannot silently regress the house style.
//
// It is intentionally data-driven over c.Root().Commands() rather than a
// hardcoded list: any command registered in entrypoint.go is swept in.
//
// A few cobra-generated builtins (`help`, the `completion` parent and its
// per-shell script generators) carry wording graft does not own; those are
// skipped for the Short-prose checks but NOT for graft's own nested commands
// (e.g. `completion install`, which graft adds).

// cobraOwnedShort reports whether cmd's Short text is owned by cobra (a builtin
// we did not author) and should therefore be exempt from the prose conventions.
func cobraOwnedShort(cmd *cobra.Command) bool {
	switch cmd.Name() {
	case "help", "completion", "bash", "zsh", "fish", "powershell":
		// The `completion` parent and its shell-script children are generated by
		// cobra's InitDefaultCompletionCmd; `install` underneath is graft's.
		return true
	default:
		return false
	}
}

// walkCommands invokes fn for cmd and every command beneath it.
func walkCommands(cmd *cobra.Command, fn func(*cobra.Command)) {
	fn(cmd)
	for _, sub := range cmd.Commands() {
		walkCommands(sub, fn)
	}
}

// usageMetachars are the characters that signal embedded usage syntax in a
// Short description. A Short must read as prose, not a usage line.
const usageMetachars = "|<>[]"

func newTestRoot() *cobra.Command {
	return cli.EntrypointWithVersion(nil, nil, "test").Root()
}

func TestCLIConsistency_Short(t *testing.T) {
	root := newTestRoot()
	walkCommands(root, func(cmd *cobra.Command) {
		if cobraOwnedShort(cmd) {
			return
		}
		path := cmd.CommandPath()
		short := cmd.Short

		if strings.TrimSpace(short) == "" {
			t.Errorf("%s: Short is empty", path)
			return
		}
		// First letter uppercase. (The root's Short is the brand tagline
		// "graft — …" which intentionally leads with the lowercase binary name;
		// exempt the root only.)
		if cmd != root {
			r := []rune(short)[0]
			if r < 'A' || r > 'Z' {
				t.Errorf("%s: Short must start with an uppercase letter, got %q", path, short)
			}
		}
		// No trailing period.
		if strings.HasSuffix(short, ".") {
			t.Errorf("%s: Short must not end with a period, got %q", path, short)
		}
		// No embedded usage syntax.
		if i := strings.IndexAny(short, usageMetachars); i >= 0 {
			t.Errorf("%s: Short contains usage metacharacter %q (no embedded usage syntax allowed): %q",
				path, string(short[i]), short)
		}
	})
}

func TestCLIConsistency_Use(t *testing.T) {
	root := newTestRoot()
	walkCommands(root, func(cmd *cobra.Command) {
		path := cmd.CommandPath()
		fields := strings.Fields(cmd.Use)
		if len(fields) == 0 {
			t.Errorf("%s: Use is empty", path)
			return
		}
		// The first token of Use must be the command's own name.
		if fields[0] != cmd.Name() {
			t.Errorf("%s: Use first token %q must equal command name %q", path, fields[0], cmd.Name())
		}
		// Use must never embed flag tokens — flags belong in the Flags section.
		for _, f := range fields {
			if strings.HasPrefix(f, "--") {
				t.Errorf("%s: Use must not contain flag tokens, found %q in %q", path, f, cmd.Use)
			}
		}
	})
}

// TestCLIConsistency_OutputFlag asserts every command that registers -o/--output
// uses the single canonical description, so the output flag reads identically
// everywhere.
func TestCLIConsistency_OutputFlag(t *testing.T) {
	const wantUsage = "Output format: json|yaml|table"
	root := newTestRoot()
	seen := 0
	walkCommands(root, func(cmd *cobra.Command) {
		f := cmd.Flags().Lookup("output")
		if f == nil {
			return
		}
		seen++
		path := cmd.CommandPath()
		if f.Shorthand != "o" {
			t.Errorf("%s: --output shorthand must be -o, got %q", path, f.Shorthand)
		}
		if f.Usage != wantUsage {
			t.Errorf("%s: --output usage must be exactly %q, got %q", path, wantUsage, f.Usage)
		}
	})
	if seen == 0 {
		t.Fatal("no command registered --output; the walk or flag wiring is broken")
	}
}

// TestCLIConsistency_ShorthandsConsistent asserts that the short-flag letters are
// not overloaded: wherever a long flag with a reserved shorthand appears it must
// use that letter, and wherever a reserved letter is used it must back the
// matching long flag. Guards against a future command reusing -o/-g/-p for
// something else.
func TestCLIConsistency_ShorthandsConsistent(t *testing.T) {
	// reserved long->short and the inverse short->long.
	longToShort := map[string]string{
		"output":   "o",
		"global":   "g",
		"provider": "p",
	}
	shortToLong := map[string]string{}
	for long, short := range longToShort {
		shortToLong[short] = long
	}

	root := newTestRoot()
	walkCommands(root, func(cmd *cobra.Command) {
		path := cmd.CommandPath()
		cmd.Flags().VisitAll(func(f *pflag.Flag) {
			// matching long flag -> must carry the reserved shorthand
			if short, ok := longToShort[f.Name]; ok && f.Shorthand != "" && f.Shorthand != short {
				t.Errorf("%s: --%s must use -%s, got -%s", path, f.Name, short, f.Shorthand)
			}
			// reserved shorthand -> must back the matching long flag
			if f.Shorthand != "" {
				if long, ok := shortToLong[f.Shorthand]; ok && f.Name != long {
					t.Errorf("%s: shorthand -%s is reserved for --%s, but backs --%s", path, f.Shorthand, long, f.Name)
				}
			}
		})
	})
}

// TestCLIConsistency_GroupsHelpExitZero asserts every command GROUP (a command
// with subcommands) renders help with no error when invoked with no args.
func TestCLIConsistency_GroupsHelpExitZero(t *testing.T) {
	root := newTestRoot()
	var groups [][]string
	walkCommands(root, func(cmd *cobra.Command) {
		if cmd == root {
			return
		}
		if len(childCommands(cmd)) > 0 {
			// Path relative to root (drop the "graft" prefix) for SetArgs.
			parts := strings.Fields(cmd.CommandPath())
			groups = append(groups, parts[1:])
		}
	})
	if len(groups) == 0 {
		t.Fatal("no command groups discovered; the walk is broken")
	}
	for _, args := range groups {
		args := args
		t.Run(strings.Join(args, "/"), func(t *testing.T) {
			// Rebuild the root per case so flag/arg state never leaks between runs.
			r := newTestRoot()
			var out, errBuf bytes.Buffer
			r.SetOut(&out)
			r.SetErr(&errBuf)
			r.SetArgs(args)
			if err := r.Execute(); err != nil {
				t.Errorf("group %v: bare invocation should render help with no error, got: %v (stderr: %s)",
					args, err, errBuf.String())
			}
		})
	}
}

// childCommands returns the non-help subcommands of cmd (cobra injects a `help`
// command into any command that has children; it is not a "real" group child).
func childCommands(cmd *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, s := range cmd.Commands() {
		if s.Name() == "help" {
			continue
		}
		out = append(out, s)
	}
	return out
}
